Repository ucsb-cs56-w20/mapache-search, pull requests merged in 2019-12, with the labels that each got.

#75 Allow /css paths to be loaded even when not logged in
  src/main/java/edu/ucsb/cs56/mapache_search/Application.java
Labels: F19-Up-Downvote

#83 db Use JS for voting
  src/main/resources/static/css/results.css
  src/main/resources/templates/fragments/bootstrap_scripts.html
  src/main/resources/templates/fragments/up_down_result_row.html
  src/main/resources/templates/searchUpDownResults.html
Labels: F19-Up-Downvote

#67 Properly encode search queries
  src/main/java/edu/ucsb/cs56/mapache_search/GoogleSearchService.java
Labels: F19-UX

#87 Aq/Db upvote downvote buttons
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchResultRepository.java
Labels: F19-UX, enhancement

#85 My/By - API Exception Handler
  .gitignore
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/search/SearchResult.java
  src/main/resources/templates/searchUpDownResults.html
Labels: enhancement

#90 db sort results by vote first, then position
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
Labels: F19-Up-Downvote, enhancement

#56 add search bar and show previous search
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/resources/templates/fragments/basic_search_form.html
  src/main/resources/templates/searchResults.html
Labels: F19-UX

#92 my - add the current API key indicator back
  src/main/resources/templates/user/settings.html
Labels: F19-Up-Downvote

#93 Ml/aq/my/db Tie users to votes
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/VoteController.java
  src/main/java/edu/ucsb/cs56/mapache_search/entities/UserVote.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/VoteRepository.java
  src/main/resources/templates/fragments/up_down_result_row.html
Labels: F19-Up-Downvote, enhancement

#74 Autofocus attribute
  src/main/java/edu/ucsb/cs56/mapache_search/AuthControllerAdvice.java
  src/main/resources/templates/fragments/basic_search_form.html
  src/main/resources/templates/user/settings.html
Labels: F19-UX, NEEDS ATTENTION

#77 Jl restyle search page
  src/main/resources/css/styles.css
  src/main/resources/templates/fragments/basic_search_form.html
  src/main/resources/templates/fragments/bootstrap_footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/searchResults.html
Labels: F19-UX, NEEDS ATTENTION

#96 ln error handling
  src/main/java/edu/ucsb/cs56/mapache_search/BasicErrorController.java
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/resources/templates/errors/401.html
  src/main/resources/templates/errors/404.html
  src/main/resources/templates/errors/500.html
  src/main/resources/templates/errors/error.html
  src/main/resources/templates/errors/notLoggedIn.html
Labels: F19-UX, NEEDS ATTENTION

#80 Jc counter for api
  src/main/java/edu/ucsb/cs56/mapache_search/Application.java
  src/main/java/edu/ucsb/cs56/mapache_search/AuthControllerAdvice.java
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/UserController.java
  src/main/java/edu/ucsb/cs56/mapache_search/entities/AppUser.java
  src/main/resources/application.properties
  src/main/resources/templates/fragments/basic_search_form.html
  src/main/resources/templates/searchResults.html
  src/main/resources/templates/user/settings.html
Labels: F19-UX, NEEDS ATTENTION

#63 Implement Pagination
  src/main/java/edu/ucsb/cs56/mapache_search/GoogleSearchService.java
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/SearchParameters.java
  src/main/java/edu/ucsb/cs56/mapache_search/SearchService.java
  src/main/java/edu/ucsb/cs56/mapache_search/search/SearchInformation.java
  src/main/java/edu/ucsb/cs56/mapache_search/search/SearchResult.java
  src/main/resources/templates/fragments/basic_search_form.html
  src/main/resources/templates/fragments/pagination.html
  src/main/resources/templates/searchResults.html
Labels: F19-UX, NEEDS ATTENTION

#88 db Pass URL info to vote endpoint
  src/main/resources/templates/fragments/up_down_result_row.html
  src/main/resources/templates/searchUpDownResults.html
Labels: F19-Up-Downvote, NEEDS ATTENTION, enhancement

#100 jl-fixed previous search input
  src/main/resources/templates/fragments/basic_search_form.html
Labels: F19-UX
