Repository ucsb-cs56-w20/mapache-search, pull requests merged in 2019-11, with the labels that each got.

#28 pc set permission 755 on setHerokuEnv.py
  setHerokuEnv.py
Labels: bug

#32 pc/aq/ml/my - add three more fields to JSON object, and make display nicer
  src/main/java/edu/ucsb/cs56/mapache_search/search/Item.java
  src/main/resources/templates/searchResults.html
Labels: enhancement

#54 db/ml added search result table, insert all new results
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/entities/SearchResultEntity.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchResultRepository.java
Labels: enhancement

#55 Restyle search results page
  src/main/java/edu/ucsb/cs56/mapache_search/search/Item.java
  src/main/resources/templates/fragments/result_row.html
  src/main/resources/templates/searchResults.html
Labels: F19-UX

#53 7PM UpDown Navbar Fixes
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/search/Item.java
  src/main/resources/templates/fragments/bootstrap_nav_header.html
  src/main/resources/templates/fragments/up_down_search_form.html
  src/main/resources/templates/searchUpDownResults.html
  src/main/resources/templates/upDownIndex.html
Labels: F19-Up-Downvote

#68 7PMUpDown display vote totals and add buttons
  src/main/java/edu/ucsb/cs56/mapache_search/SearchController.java
  src/main/resources/static/css/results.css
  src/main/resources/templates/fragments/bootstrap_head.html
  src/main/resources/templates/fragments/up_down_result_row.html
  src/main/resources/templates/searchUpDownResults.html
Labels: F19-Up-Downvote, enhancement
