Repository ucsb-cs56-w20/mapache-search, pull requests merged in 2020-03, with the labels that each got.

#266 bo - API Uses bugs
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/SearchController.java
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/UserController.java
Labels: MergeConflicts

#261 Resolved Index Out Of Bounds
  src/main/java/edu/ucsb/cs56/mapache_search/preview/PreviewProviderServiceImpl.java
Labels: ReadyForReview

#277 W 7pm a user permissions
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/InstructorController.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/UserRepository.java
  src/main/resources/templates/instructor/add_instructor.html
  src/main/resources/templates/instructor/index.html
Labels: ReadyForReview

#240 eg/bk - able to save link data: user id , time , and url
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/LinkController.java
  src/main/java/edu/ucsb/cs56/mapache_search/entities/Link.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/LinkRepository.java
  src/test/java/edu/ucsb/cs56/mapache_search/LinkControllerTest.java
  src/test/java/edu/ucsb/cs56/mapache_search/OAuthUtils.java
Labels: Failing Tests

#276 ap/tc Removed Sort by highest upvotes option in filter interface
  src/main/resources/templates/fragments/filtered_search_form.html
Labels: MergeConflicts

#264 W 7pm a random student
  .gitignore
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/InstructorController.java
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/UpvoteHistoryController.java
  src/main/java/edu/ucsb/cs56/mapache_search/controllers/UserController.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/SearchQueriesRepository.java
  src/main/java/edu/ucsb/cs56/mapache_search/repositories/UserRepository.java
  src/main/resources/templates/instructor/index.html
  src/main/resources/templates/instructor/random_student_generator.html
  src/main/resources/templates/instructor/random_student_results.html
Labels: ReadyForReview
